# Generated by Django 4.2.5 on 2023-09-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_weapons_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapons',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='scaling',
        ),
    ]
