# Generated by Django 4.2.5 on 2023-09-20 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_weapons_requirements_remove_weapons_scaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
